question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.",
        "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space with the naked eye.",
        "answer": "False"},
    {"text": "Bananas are berries.", "answer": "True"},
    {"text": "The Eiffel Tower was originally intended for Barcelona, Spain.",
        "answer": "False"},
    {"text": "Cats have five toes on their front paws but only four toes on their back paws.", "answer": "True"},
    {"text": "The longest river in the world is the Amazon River.", "answer": "True"},
    {"text": "Penguins are mammals.", "answer": "False"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "The Earth is approximately 4.5 billion years old.", "answer": "True"},
    {"text": "The largest desert in the world is Antarctica.", "answer": "True"},
    {"text": "There are more stars in the universe than grains of sand on Earth.", "answer": "True"}
]
